environment:
  MAJOR: 27
  MINOR: 2
  PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

init:
  - ps: Update-AppveyorBuild -Version "$env:MAJOR.$env:MINOR-$(Get-Date -format yyyyMMdd).$env:appveyor_build_number"

branches:
  only:
    - master

cache:
  - src

build_script:
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman --noconfirm -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "rm -r /etc/pacman.d/gnupg/"
  - bash -lc "pacman-key --init"
  - bash -lc "pacman-key --populate msys2"
#  - bash -lc "pacman --noconfirm -Sydd pacman"
  - bash -lc "pacman --noconfirm -Syu"
  - bash -lc "pacman --noconfirm -S base"
  - bash -lc "pacman --noconfirm -Syu"
  - chcp 65001 && bash -ex build.sh %MAJOR%.%MINOR% /c/projects/ntemacs64/emacs%MAJOR% /c/projects/ntemacs64

artifacts:
  - path: emacs%MAJOR%
    name: ntemacs64-%MAJOR%.%MINOR%

deploy:
  provider: GitHub
  auth_token:
    secure: smgA9XrXqqqHlyA1Df/T7xOYo6OcPi5974y8AxRJjlYLidg5mtCwCYEKLMQs8Dsx
  artifact: /ntemacs64-.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

