environment:
  MAJOR: 26
  MINOR: 2
  PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

init:
  - ps: Update-AppveyorBuild -Version "$env:MAJOR.$env:MINOR-$(Get-Date -format yyyyMMdd).$env:appveyor_build_number"

branches:
  only:
    - master

cache:
  - src

build_script:
  - chcp 65001 && bash -ex build.sh %MAJOR%.%MINOR% /c/projects/ntemacs64/emacs%MAJOR% /c/projects/ntemacs64

artifacts:
  - path: emacs26
    name: ntemacs64-%MAJOR%.%MINOR%

deploy:
  provider: GitHub
  auth_token:
    secure: smgA9XrXqqqHlyA1Df/T7xOYo6OcPi5974y8AxRJjlYLidg5mtCwCYEKLMQs8Dsx
  artifact: /ntemacs64-.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

